---

- name: Ansible sync via NSO
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: NSO sync-from task
      nso_action:
        url: "http://localhost:8080/jsonrpc"
        username: "admin"
        password: "admin"
        path: /ncs:devices/sync-from
        input: {}
